<?php
use Application\Model\Constants;
echo $this->doctype(); ?>

    <html lang="en">
<!-- saved from url=(0051)https://tarruda.github.io/bootstrap-datetimepicker/ -->
<html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Date/Time Picker for Twitter Bootstrap">

    <meta name="author" content="Alois Mumera mumeraalois@gmail.com">
    <title>Ecocash Payments</title>
    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
    echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ->prependStylesheet($this->basePath('bower_components/metisMenu/dist/metisMenu.min.css'))
        ->prependStylesheet($this->basePath('css/sb-admin-2.css'))
        ->prependStylesheet($this->basePath('css/datepicker.min.css'))
        ->prependStylesheet($this->basePath('css/datepicker3.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.css'))
        ->prependStylesheet($this->basePath('bower_components/font-awesome/css/font-awesome.min.css'))
        ->prependStylesheet($this->basePath('bower_components/bootstrap/dist/css/bootstrap.css' ))
        ->prependStylesheet($this->basePath('css/bootstrap-timepicker.min.css'))
        ->prependStylesheet($this->basePath('BootstrapDate_TimePicker_files/js/bootstrap-datetimepicker.min.css' ));
    // <!-- Scripts -->
     echo $this->headScript()
        ->prependFile($this->basePath('BootstrapDate_TimePicker_files/jquery.min.js'))
        ->prependFile($this->basePath('BootstrapDate_TimePicker_files/bootstrap.min.js'))
        ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',)); ?>
</head>
    <body>
<?php
use Application\Entity\EcocashPayments;
use Mobile\Model\Utils;


$url_links = array(
    'dashboard'=>$this->url('dashboard', array('controller'=>'WebDashboard', 'action'=>Constants::DASH_VIEW)),
    'users'=>$this->url('dashboard', array('controller'=>'WebDashboard', 'action'=>Constants::SHIRI_USERS)),
    'eco_pay'=>$this->url('dashboard', array('controller'=>'WebDashboard', 'action'=>Constants::ECOCASH_PAYMENT)),
    'net_pay'=>$this->url('dashboard', array('controller'=>'WebDashboard', 'action'=>Constants::NETTCASH_PAYMENT)),
    'msgs'=>$this->url('dashboard', array('controller'=>'WebDashboard', 'action'=>Constants::MESSAGES)),
    'change_password'=>$this->url('dashboard', array('controller'=>'WebDashboard', 'action'=>Constants::CHANGE_PASSWORD)),
    'api_connect'=>$this->url('dashboard', array('controller'=>'WebDashboard', 'action'=>Constants::API_CONNECT)),
    'send_notification'=>$this->url('dashboard', array('controller'=>'WebDashboard', 'action'=>Constants::SEND_NOTIFICATION)),
    'send_news'=>$this->url('dashboard', array('controller'=>'WebDashboard', 'action'=>Constants::SEND_NEWS)),
    'home'=>$this->url('dashboard', array('controller'=>'WebDashboard', 'action'=>Constants::DASH_BOARD)),
    'logout'=>$this->url('admin', array('controller'=>'Website', 'action'=>Constants::LOG_OUT))
);

$viewState = 0;
if($this->state){
    $viewState = $this->state;
}


?>
    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?php  echo $url_links['api_connect'] ?>"><?php  echo \Application\Model\Constants::SHIRI_ADMIN_PANEL ?></a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">

                <!-- /.user dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                        </li>

                        <li class="divider"></li>
                        <li><a href="<?php  echo $url_links['logout'] ?>"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li class="sidebar-search">
                            <div class="input-group custom-search-form">
                                <input type="text" class="form-control" placeholder="Search...">
                                <span class="input-group-btn">
                                <button class="btn btn-default" type="button">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                            </div>
                            <!-- /input-group -->
                        </li>
                        <li>
                            <a href="<?php  echo $url_links['dashboard'] ?>"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                        </li>
                        <li>
                            <a href="<?php  echo $url_links['users'] ?>"><i class="fa fa-user fa-fw"></i> Users</a>

                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="<?php  echo $url_links['eco_pay'] ?>"><i class="fa fa-dollar fa-fw"></i> Ecocash Payments<span class="fa arrow"></span></a>
                        </li>
                        <li>
                            <a href="<?php  echo $url_links['net_pay'] ?>"><i class="fa fa-dollar fa-fw"></i> Netcash Payments</a>
                        </li>
                        <li>
                            <a href="<?php  echo $url_links['msgs'] ?>"><i class="fa fa-envelope fa-fw"></i> Messages</a>

                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="<?php  echo $url_links['change_password'] ?>"><i class="fa fa-lock fa-fw"></i> Change Password</a>

                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="<?php  echo $url_links['api_connect'] ?>"><i class="fa fa-external-link fa-fw"></i> API Connect</span></a>

                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="<?php  echo $url_links['send_notification'] ?>"><i class="fa fa-bell fa-fw"></i> Send Notification</a>

                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="<?php  echo $url_links['send_news'] ?>"><i class="fa fa-cloud fa-fw"></i> Send News</span></a>

                            <!-- /.nav-second-level -->
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <p><br/></p>
                    <?php if($viewState == 0){ ?>
                <a class="btn btn-default btn-lg btn-block" href="<?php
                $btn_url =  $url_links['eco_pay']. Constants::PAGE_0.Constants::ECO_1431;
                echo $btn_url?>">Save Ecocash Payment</a>
                <p><div style="text-align: center;"><hr width ="700"/></div></p>
<?php }?>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row"></div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">

                    <div class=" panel panel-default">
                        <div class="panel-heading">
                            <i class=" fa-fw"></i>
                            Ecocash Payments
                            <div class="btn-group pull-right">

                            </div>
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <?php if($viewState == Constants::SAVE_ECO_PAYMENT){ ?>

                                <form role="form" method="post" action="<?php
                                $btn_url =  $url_links['eco_pay']. Constants::PAGE_0.Constants::ECO_1432;
                                echo $btn_url;?>">
                                    <label> Amount</label>
                                    <div class="form-group input-group">
                                        <span class="input-group-addon">$</span>
                                        <input type="text" class="form-control" name = "amount" required = "true" placeholder="Enter Amount">

                                    </div>
                                    <label>Excess Amount</label>
                                    <div class="form-group input-group">
                                        <span class="input-group-addon">$</span>
                                        <input type="text" class="form-control" name = "examount" required = "true" placeholder="Enter Excess Amount">

                                    </div>
                                    <div >

                                        <table align="center" width="100%" cellpadding="0" cellspacing="0" border="0">
                                            <tr>
                                                <td><label> Date Paid</label></td>
                                                <td>

                                                    <div class="input-group input-append date" id="datePicker">
                                                        <input class="form-control" name = "dtpaid" required = "true" placeholder="Date"/>
                                                        <span class="add-on"></span>

                                                    </div>
                                                </td>
                                                <td><label> Time</label></td>
                                                <td>



                                                        <div class="input-append" id="datetimepicker3">
                                                            <input data-format="hh:mm:ss" type="text" class="form-control input-small" name = "dtTime" required = "true" placeholder="Time"/>
                                                            <span class="add-on">
                                                     <i data-date-icon="icon-calendar" data-time-icon="icon-time" class="icon-time">
                                                     </i>
                                                            </span>


                                                </td>
                                            </tr>

                                        </table>

                                    </div>
                                    <div class="form-group">

                                        <label> Reference Number</label>
                                        <input class="form-control" name = "refNumber" required = "true" placeholder="Enter Reference Number">

                                    </div>
                                    <div class="form-group">

                                        <label> Phone Number</label>
                                        <input class="form-control" name = "phoneNumber" required = "true" value="+263" placeholder="Enter Phone Number">

                                    </div>

                                    <div class="form-group">
                                        <a href="<?php echo $url_links['eco_pay']?>" class="btn btn-primary">back</a>
                                        <input id="submit" name="submit" type="submit" value="Save Payment" class="btn btn-primary">
                                    </div>
                                </form>

                            <?php }else if($viewState == Constants::CONFIRM_PAYMENT){  ?>

                            <?php }else{  ?>
                                <div class=" table-responsive">

                                    <table class="table table-striped table-hover table-condensed">
                                        <thead>

                                        <tr>
                                            <th>#</th>
                                            <th>Name</th>
                                            <th>Amount paid</th>
                                            <th>Date Paid</th>
                                            <th>Reference Number</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <?php
                                        $util = new Utils();
                                        foreach ($this->payments as $payment):

                                            // $payment = new EcocashPayments();
                                            $user = $payment->getUser();
                                            //  $user = new Users();
                                            $username = $user->getFirstName(). ' '.$user->getLastName();
                                            $paidAt_date = $payment->getDatePaid();
                                            $paidAt_date = $paidAt_date->format('Y-m-d H:m:s');
                                            //$date_paid = $util->MillisecondsToDateTimeString($payment->getDatePaid()*1000,0);
                                            ?>

                                            <tr>
                                                <td><?php echo $this->escapeHtml($payment->getId()); ?></td>
                                                <td><?php echo $this->escapeHtml($username); ?></td>
                                                <td><?php echo $this->escapeHtml(number_format($payment->getAmountPaid(),Constants::TWO_DECIMAL_PLACE)); ?></td>
                                                <td><?php echo $this->escapeHtml($paidAt_date); ?></td>
                                                <td><?php echo $this->escapeHtml($payment->getReferenceId()); ?></td>
                                            </tr>
                                        <?php endforeach; ?>
                                        </tbody>
                                    </table>
                                </div>

                                <?php echo $this->paginationControl($this->payments, 'Sliding', 'paginator.phtml',
                                    array('controllerAction'=>Constants::ECOCASH_PAYMENT)); ?>

                            <?php }?>


                        </div>
                        <!-- /.panel-body -->
                        <div class="panel-footer">

                        </div>
                        <!-- /.panel-footer -->
                    </div>

                </div>
                <!-- /.col-lg-8 -->
                <div class="col-lg-4">



                </div>
                <!-- /.col-lg-4 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->

    </div>
<?php
$this->inlineScript()
    ->prependFile($this->basePath('css/bootstrap-datepicker.min.js'))
    ->prependFile($this->basePath('BootstrapDate_TimePicker_files/bootstrap-datetimepicker.min.js'))
    ->prependFile($this->basePath('BootstrapDate_TimePicker_files/bootstrap-datetimepicker.pt-BR.js'));
$this->inlineScript()->captureStart();
echo <<<JS
  $(function() {
                    $('#datetimepicker3').datetimepicker({
                        pickDate: false
                    });
                });
   $(document).ready(function() {

    $('#datePicker')
        .datepicker({
            format: 'yyyy-m-d',
        autoclose: true,
        todayBtn: true,
        pickerPosition: "bottom-left"
        });
 $('#timepicker2').timepicker({
                minuteStep: 1,
                template: 'modal',
                appendWidgetTo: 'body',
                showSeconds: true,
                showMeridian: false,
                defaultTime: false
            });

});

JS;
$this->inlineScript()->captureEnd();
echo $this->inlineScript();

?>


<?= $this->render('layout/footer.phtml') ?>