<body id="login">
<div class="container">
<?php
$url_links = array(
    'register'=>$this->url('admin', array('controller'=>'Website', 'action'=>'registerAdminUser')),
    'login'=>$this->url('admin', array('controller'=>'Website', 'action'=>'login'))
);

?>
    <p style="vertical-align:middle">
    <center><h3 class="muted">Shiri Web Service</h3></center>
    <p><center><br/></center></p>
    <p><center><hr width ="700"/></center></p>
    <!-- <center><marquee behavior="alternate"><h1>Welcome to the Shiri App Admin Monitoring Panel</h1></marquee></center>-->
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
    <center>

<!--        <form method="post" action="index.php" name="loginform" class="form-signin" style="width:250px; border:solid 1px #cccccc; border-style:ridge; padding: 20px;">-->
<!--            <h2 class="form-signin-heading">Admin Panel</h2>-->
<!--            <input type="text" id="login_input_username" name="user_name" class="input-block-level"  placeholder="Username" required />-->
<!--            <input type="password" id="login_input_password" name="user_password" class="input-block-level" placeholder="Password" autocomplete="off" required />-->
<!--            <label class="checkbox">-->
<!--                <input type="checkbox" value="remember-me"> Remember me-->
<!--            </label>-->
<!--            <input class="btn btn-large btn-primary" name="login" type="submit" value="Sign in">-->
<!--        </form>-->
<!---->
<!--        <a href= "--><?php // echo $url_links['register'] ?><!--">Register new account</a>-->
        <?php
        $form = $this->form;
        $form->setAttributes(array('action' =>$url_links['login'],
            'method'=>'post',
            'class'=>'login-panel panel panel-default',
            'style'=>'width:250px;  padding: 20px;'
        ))
            ->prepare();
        echo $this->form()->openTag($form);
        if ($this->data){
            if($this->data['name'])
                $form->get('username')->setValue($this->data['name']);

        }
        echo $this->formCollection($form);
        echo $this->form()->closeTag();

        if ($this->messages){
//            echo '<ul>';
//            foreach($this->messages as $message)
//            {
//                echo '<li>'.$message.'</li>';
//            }
//            echo '</ul>';
            $flash = $this->flashMessenger();

            echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
//            echo $flash->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
//            echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
//            echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
        }

        ?>
                <a href= "<?php  echo $url_links['register'] ?>">Register new account</a>
    </center>
                </div></div></div>
    <p><center><hr width ="700"/></center></p>

    </p>

</div> <!-- /container -->

<!--</body>-->
<div id="footer"><?= $this->render('layout/footer.phtml') ?></div>
