<?= $this->render('layout/header.phtml') ?>
</head>
<body>
<?php
use Application\Model\Constants;
use Mobile\Model\Utils;

$util = new Utils();
$url_links = array(
    'dashboard'=>$this->url('dashboard', array('controller'=>'WebDashboard', 'action'=>Constants::DASH_VIEW)),
    'users'=>$this->url('dashboard', array('controller'=>'WebDashboard', 'action'=>Constants::SHIRI_USERS)),
    'eco_pay'=>$this->url('dashboard', array('controller'=>'WebDashboard', 'action'=>Constants::ECOCASH_PAYMENT)),
    'net_pay'=>$this->url('dashboard', array('controller'=>'WebDashboard', 'action'=>Constants::NETTCASH_PAYMENT)),
    'msgs'=>$this->url('dashboard', array('controller'=>'WebDashboard', 'action'=>Constants::MESSAGES)),
    'change_password'=>$this->url('dashboard', array('controller'=>'WebDashboard', 'action'=>Constants::CHANGE_PASSWORD)),
    'api_connect'=>$this->url('dashboard', array('controller'=>'WebDashboard', 'action'=>Constants::API_CONNECT)),
    'send_notification'=>$this->url('dashboard', array('controller'=>'WebDashboard', 'action'=>Constants::SEND_NOTIFICATION)),
    'send_news'=>$this->url('dashboard', array('controller'=>'WebDashboard', 'action'=>Constants::SEND_NEWS)),
    'home'=>$this->url('dashboard', array('controller'=>'WebDashboard', 'action'=>Constants::DASH_BOARD)),
    'logout'=>$this->url('admin', array('controller'=>'Website', 'action'=>Constants::LOG_OUT)),
    'sendSMS'=>$this->url('dashboard', array('controller'=>'WebDashboard', 'action'=>'sendSMStoUser')),
    'sendNotif'=>$this->url('dashboard', array('controller'=>'WebDashboard', 'action'=>'sendNotifToUser'))
);
$viewState = 0;
if($this->ViewState) {
    $viewState = $this->ViewState;
    $UserData = $this->UserData;
}
$result_state = -1;
if($this->message){
    $msgs = $this->message;
    $Msg =  $msgs['msg'];
    $result_state =  $msgs['state'];
    $title =  $msgs['title'];
    $errtitle =  $msgs['ErrTitle'];
    $message =  $msgs['msgTobSent'];
}
?>
<div id="wrapper">

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php  echo $url_links['api_connect'] ?>"><?php  echo \Application\Model\Constants::SHIRI_ADMIN_PANEL ?></a>
        </div>
        <!-- /.navbar-header -->

        <ul class="nav navbar-top-links navbar-right">

            <!-- /.user dropdown -->
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
                </a>
                <ul class="dropdown-menu dropdown-user">
                    <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                    </li>

                    <li class="divider"></li>
                    <li><a href="<?php  echo $url_links['logout'] ?>"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                    </li>
                </ul>
                <!-- /.dropdown-user -->
            </li>
            <!-- /.dropdown -->
        </ul>
        <!-- /.navbar-top-links -->

        <div class="navbar-default sidebar" role="navigation">
            <div class="sidebar-nav navbar-collapse">
                <ul class="nav" id="side-menu">
                    <li class="sidebar-search">
                        <div class="input-group custom-search-form">
                            <input type="text" class="form-control" placeholder="Search...">
                                <span class="input-group-btn">
                                <button class="btn btn-default" type="button">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                        </div>
                        <!-- /input-group -->
                    </li>
                    <li>
                        <a href="<?php  echo $url_links['dashboard'] ?>"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                    </li>
                    <li>
                        <a href="<?php  echo $url_links['users'] ?>"><i class="fa fa-user fa-fw"></i> Users</a>

                        <!-- /.nav-second-level -->
                    </li>
                    <li>
                        <a href="<?php  echo $url_links['eco_pay'] ?>"><i class="fa fa-dollar fa-fw"></i> Ecocash Payments</a>
                    </li>
                    <li>
                        <a href="<?php  echo $url_links['net_pay'] ?>"><i class="fa fa-dollar fa-fw"></i> Netcash Payments</a>
                    </li>
                    <li>
                        <a href="<?php  echo $url_links['msgs'] ?>"><i class="fa fa-envelope fa-fw"></i> Messages</a>

                        <!-- /.nav-second-level -->
                    </li>
                    <li>
                        <a href="<?php  echo $url_links['change_password'] ?>"><i class="fa fa-lock fa-fw"></i> Change Password</a>

                        <!-- /.nav-second-level -->
                    </li>
                    <li>
                        <a href="<?php  echo $url_links['api_connect'] ?>"><i class="fa fa-external-link fa-fw"></i> API Connect</span></a>

                        <!-- /.nav-second-level -->
                    </li>
                    <li>
                        <a href="<?php  echo $url_links['send_notification'] ?>"><i class="fa fa-bell fa-fw"></i> Send Notification<span class="fa arrow"></span></a>

                        <!-- /.nav-second-level -->
                    </li>
                    <li>
                        <a href="<?php  echo $url_links['send_news'] ?>"><i class="fa fa-cloud fa-fw"></i> Send News</span></a>

                        <!-- /.nav-second-level -->
                    </li>
                </ul>
            </div>
            <!-- /.sidebar-collapse -->
        </div>
        <!-- /.navbar-static-side -->
    </nav>

    <div id="page-wrapper">
        <!-- /.row -->
        <div class="row"><br/></div>
        <!-- /.row -->
        <div class="row">
            <div class="col-lg-12">

                <!-- /alois.panel -->
                <!--<div class="panel panel-default">-->
                <!--<div class="panel-heading">-->
                <!--<i class="fa fa-clock-o fa-fw"></i> Responsive Timeline-->
                <!--</div>-->
                <!--&lt;!&ndash; /.panel-heading &ndash;&gt;-->
                <!--<div class="panel-body"></div>-->
                <!--&lt;!&ndash; /.panel-body &ndash;&gt;-->
                <!--</div>-->
                <!-- /end alois.panel -->

                <div class="chat-panel panel panel-default">
                    <div class="panel-heading">
                        <i class=" fa-fw"></i>
                        Send Notification to individual Shiri user
                        <div class="btn-group pull-right">

                        </div>
                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">

                        <?php if($viewState == Constants::SEND_SMS_TO_USER){?>
                            <div class="row">
                                <div class="col-lg-6">
                                <div class="alert alert-info">
                                    Send SMS to <?php
                                    // $UserData = new \Application\Entity\Users();
                                    $user_full_name = $UserData->getFirstName(). ' '. $UserData->getLastName();
                                    echo $this->escapeHtml($user_full_name);
                                    ?> <button type="button"  class="btn btn-info btn-circle" data-toggle="modal" data-target="#myModal">
                                        <i class="fa fa-info"></i>
                                    </button>

                                    <!-- Modal -->
                                    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                                    <h4 class="modal-title" id="myModalLabel"><?php echo $this->escapeHtml($user_full_name.' Details');?></h4>
                                                </div>
                                                <div class="modal-body">
                                                    <p>
                                                        Full Name : <?php echo $this->escapeHtml($user_full_name); ?>
                                                    </p>
                                                    <p>
                                                        Phone Number : <?php echo $this->escapeHtml($UserData->getPhoneNumber()); ?>
                                                    </p>
                                                    <p>
                                                        Date of Birth : <?php
                                                        $dob =  $util->toWordsDtString($UserData->getDateOfBirth(),
                                                            Constants::SHOW_DATE_OF_BIRTH);
                                                        echo $this->escapeHtml($dob);
                                                        ?>
                                                    </p>
                                                    <p>
                                                        Date Joined : <?php
                                                        $jdate = $util->toWordsDtString($UserData->getCreatedAt(),0);
                                                        echo $this->escapeHtml($jdate);
                                                        ?>
                                                    </p>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>

                                                </div>
                                            </div></div>
                                        <!-- /.modal-content -->
                                    </div>

                                </div>

                                    <form role="form" method="post" action="<?php echo $url_links['sendSMS']?>">

                                        <div class="form-group hidden">
                                            <input type="hidden" name="phoneNumber" value="<?php echo $UserData->getPhoneNumber(); ?>"/>
                                        </div>
                                        <div class="form-group">
                                            <?php
                                            $message_placeholder = Constants::NOTIFICATION_SMS;
                                            $label = 'Message';
                                            if($result_state == Constants::ERROR){
                                                $message_placeholder = $message;
                                                $label =  $Msg;?>

                                                    <div class="alert alert-danger  alert-dismissable -align-center">
                                                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                                        <?php echo  $this->escapeHtml($label);?>
                                                    </div>

                                                <textarea class="form-control"  required = "true" name="message" rows="3"><?php echo $this->escapeHtml($message_placeholder);?></textarea>

                                            <?php }else if($result_state == Constants::INT_SUCCESS){
                                                $label =  $Msg;?>
                                                  <div class="alert alert-success alert-dismissable">
                                                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                                        <?php echo  $this->escapeHtml($label.' to '.$user_full_name);?>
                                                    </div>
                                                <textarea class="form-control"  required = "true"  name="message" rows="3" placeholder="<?php echo Constants::NOTIFICATION_SMS?>"></textarea>

                                            <?php }else { ?>
                                                <label> <?php echo  $this->escapeHtml($label);?></label>
                                                <textarea class="form-control"  required = "true"  name="message" rows="3" placeholder="<?php echo Constants::NOTIFICATION_SMS?>"></textarea>

                                            <?php


                                            }?>

                                        </div>
                                        <div class="form-group">
                                            <a href="<?php echo $url_links['send_notification']?>" class="btn btn-primary">back</a>
                                            <input id="submit" name="submit" type="submit" value="Send SMS" class="btn btn-primary">
                                        </div>
                                    </form>
                                </div>
                            </div>
                        <?php } elseif ($viewState == Constants::SEND_NOTIF_TO_USER){ ?>
                            <div class="row">
                                <div class="col-lg-6">
                                <div class="alert alert-info">
                                    Send Notification to <?php
                                    // $UserData = new \Application\Entity\Users();
                                    $user_full_name = $UserData->getFirstName(). ' '. $UserData->getLastName();
                                    echo $user_full_name;
                                    ?> <button type="button"  class="btn btn-info btn-circle" data-toggle="modal" data-target="#myModal">
                                        <i class="fa fa-info"></i>
                                    </button>

                                    <!-- Modal -->
                                    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                                    <h4 class="modal-title" id="myModalLabel"><?php echo $user_full_name.' Details';?></h4>
                                                </div>
                                                <div class="modal-body">
                                                    <p>
                                                        Full Name : <?php echo $user_full_name; ?>
                                                    </p>
                                                    <p>
                                                        Phone Number : <?php echo $UserData->getPhoneNumber(); ?>
                                                    </p>
                                                    <p>
                                                        Date of Birth : <?php
                                                        echo $util->toWordsDtString($UserData->getDateOfBirth(),
                                                            Constants::SHOW_DATE_OF_BIRTH);
                                                        ?>
                                                    </p>
                                                    <p>
                                                        Date Joined : <?php
                                                        echo $util->toWordsDtString($UserData->getCreatedAt(),0);
                                                        ?>
                                                    </p>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>

                                                </div>
                                            </div></div>
                                        <!-- /.modal-content -->
                                    </div>

                                </div>

                                    <form role="form" method="post" action="<?php echo $url_links['sendNotif']?>">

                                        <div class="form-group hidden">
                                            <input type="hidden" name="phoneNumber" value="<?php echo $UserData->getPhoneNumber(); ?>"/>
                                            <input type="hidden" name="gcmId" value="<?php echo $UserData->getGcmRegid(); ?>"/>
                                        </div>

                                        <?php
                                        $message_placeholder = Constants::NOTIFICATION_MSG;
                                        $title_placeholder = 'Enter title';
                                        $mlabel = 'Message';
                                        $tlabel = 'Title';
                                        if($result_state == Constants::ERROR){
                                            $message_placeholder = $message;
                                            $title_placeholder = $title;
                                            $mlabel =  $Msg;
                                            $tlabel =  $errtitle;?>
                                            
                                        <div class="form-group">
                                                <label>

                                                      <?php echo  $this->escapeHtml($tlabel);?>

                                                </label>
                                                <input class="form-control" name = "title" value = "<?php echo  $this->escapeHtml($title_placeholder);?>" required = "true" placeholder="Enter title">

                                            </div>
                                            <div class="form-group">
                                                <label>
                                                    <?php echo  $this->escapeHtml($mlabel);?>

                                                </label>
                                                <textarea class="form-control"  required = "true"  name="message" rows="3" placeholder="<?php echo Constants::NOTIFICATION_MSG?>"><?php echo $this->escapeHtml($message_placeholder);?></textarea>

                                            </div>
                                        <?php }else if($result_state == Constants::INT_SUCCESS){
                                            $mlabel =  $Msg;?>
                                            <div class="alert alert-success alert-dismissable">
                                                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                                    <?php echo  $this->escapeHtml($mlabel.' to '.$user_full_name);?>
                                                </div>
                                           <div class="form-group">

                                               <label> <?php echo  $this->escapeHtml($tlabel);?></label>
                                                <input class="form-control" name = "title" required = "true" placeholder="Enter title">

                                            </div>
                                            <div class="form-group">

                                                <label> Message</label>
                                                <textarea class="form-control"  required = "true"  name="message" rows="3" placeholder="<?php echo Constants::NOTIFICATION_MSG?>"></textarea>

                                            </div>
                                        <?php }else { ?>
                                          
                                            <div class="form-group">

                                                <label> <?php echo  $this->escapeHtml($tlabel);?></label>
                                                <input class="form-control" name = "title" required = "true" placeholder="Enter title">

                                            </div>
                                            <div class="form-group">

                                                <label> <?php echo  $this->escapeHtml($mlabel);?></label>
                                                <textarea class="form-control"  required = "true"  name="message" rows="3" placeholder="<?php echo Constants::NOTIFICATION_MSG?>"></textarea>

                                            </div>
                                        <?php }?>
                                        

                                        <div class="form-group">
                                            <a href="<?php echo $url_links['send_notification']?>" class="btn btn-primary">back</a>
                                            <input id="submit" name="submit" type="submit" value="Send Notification" class="btn btn-primary">
                                        </div>
                                    </form>
                                </div>
                            </div>
                        <?php }else{?>

                            <div class=" table-responsive">

                                <table class="table table-striped table-hover table-condensed">
                                    <thead>

                                    <tr>
                                        <th>#</th>
                                        <th>Name</th>
                                        <th>Phone Number</th>
                                        <th>Branch</th>
                                        <th>Actions</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <?php
                                    $btn_url =  $url_links['send_notification']. Constants::PAGE_0;
                                    $btn_sms_url =  $url_links['send_notification']. Constants::PAGE_0;

                                    foreach ($this->users as $user):
                                     //   $user = new \Application\Entity\Users();
                                        $phoneNumber = $user->getPhoneNumber();
                                        $gcm_reg_id = $user->getGcmRegid();
                                        $user_full_name = $user->getFirstName().' '.$user->getLastName();
                                        $phoneNumber = str_replace("+","",$phoneNumber);
                                        $btn_url1 = $btn_url.$phoneNumber.':'.Constants::SEND_NOTIF_TO_USER;
                                        $btn_sms_url1 = $btn_sms_url.$phoneNumber.':'.Constants::SEND_SMS_TO_USER;
                                        $branch = $user->getBranch();
                                        ?>
                                        <tr>
                                            <td><?php echo $this->escapeHtml($user->getUserId()) ?></td>
                                            <td><?php echo $this->escapeHtml($user_full_name) ?></td>
                                            <td><?php echo $this->escapeHtml($user->getPhoneNumber()) ?></td>
                                            <td><?php echo $this->escapeHtml($branch->getBranchName()); ?></td>
                                            <td><?php echo "<td>
                                                    <p>
                                                  <a href='$btn_url1' class='btn btn-primary btn-xs'> Send Notification</a>
                                                  <a href='$btn_sms_url1' class='btn btn-info btn-xs'> Send SMS</a>
										          </p>
										  </td>"; ?></td>
                                        </tr>
                                    <?php endforeach; ?>
                                    </tbody>
                                </table>
                            </div>
                        <?php }?>
                    </div>
                    <div class="panel-footer">

                        <?php  if ($viewState == 0){
                            echo $this->paginationControl($this->users, 'Sliding', 'paginator.phtml',
                                array('controllerAction'=>Constants::SEND_NOTIFICATION));

                        } ?>

                        <!--                        <a class="btn btn-default btn-lg btn-block" target="_blank" href="#">View All Users</a>-->


                    </div>

                </div>

            </div>
            <!-- /.col-lg-8 -->
            <div class="col-lg-4">

            </div>
            <!-- /.col-lg-4 -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /#page-wrapper -->

</div>


<div id="footer"><?= $this->render('layout/footer.phtml') ?></div>