<div class=" table-responsive">

    <table class="table table-striped table-hover table-condensed">
        <thead>

        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Phone Number</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($this->users as $user): ?>
            <tr>
                <td><?php echo $this->escapeHtml($user['userId']) ?></td>
                <td><?php echo $this->escapeHtml($user['firstName'].' '.$user['lastName']) ?></td>
                <td><?php echo $this->escapeHtml($user['phoneNumber']) ?></td>
                <td><?php echo "<td>
                                                    <p>
                                                  <a href='#' class='btn btn-primary btn-xs'><i class='icon-eye-open icon-white'></i> Send Notification</a>
                                                  <a href='#' class='btn btn-info btn-xs'><i class='icon-eye-open icon-white'></i> Send SMS</a>
										          </p>
										  </td>"; ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>