<?=
    $this->render('layout/header.phtml');
    echo $this->inlineScript();
     ?>
</head>
<body>
<?php
use Application\Model\Constants;
use Mobile\Model\Utils;

$util = new Utils();
$url_links = array(
    'dashboard'=>$this->url('dashboard', array('controller'=>'WebDashboard', 'action'=>Constants::DASH_VIEW)),
    'users'=>$this->url('dashboard', array('controller'=>'WebDashboard', 'action'=>Constants::SHIRI_USERS)),
    'eco_pay'=>$this->url('dashboard', array('controller'=>'WebDashboard', 'action'=>Constants::ECOCASH_PAYMENT)),
    'net_pay'=>$this->url('dashboard', array('controller'=>'WebDashboard', 'action'=>Constants::NETTCASH_PAYMENT)),
    'msgs'=>$this->url('dashboard', array('controller'=>'WebDashboard', 'action'=>Constants::MESSAGES)),
    'change_password'=>$this->url('dashboard', array('controller'=>'WebDashboard', 'action'=>Constants::CHANGE_PASSWORD)),
    'api_connect'=>$this->url('dashboard', array('controller'=>'WebDashboard', 'action'=>Constants::API_CONNECT)),
    'send_notification'=>$this->url('dashboard', array('controller'=>'WebDashboard', 'action'=>Constants::SEND_NOTIFICATION)),
    'send_news'=>$this->url('dashboard', array('controller'=>'WebDashboard', 'action'=>Constants::SEND_NEWS)),
    'home'=>$this->url('dashboard', array('controller'=>'WebDashboard', 'action'=>Constants::DASH_BOARD)),
    'logout'=>$this->url('admin', array('controller'=>'Website', 'action'=>Constants::LOG_OUT))
);
$state = 0;
$data = array();
if($this->data) {
    $state = $this->data['state'];
    $data = $this->data['userDt'];
}

?>
<div id="wrapper">

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php  echo $url_links['api_connect'] ?>"><?php  echo Constants::SHIRI_ADMIN_PANEL ?></a>
        </div>
        <!-- /.navbar-header -->

        <ul class="nav navbar-top-links navbar-right">

            <!-- /.user dropdown -->
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
                </a>
                <ul class="dropdown-menu dropdown-user">
                    <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                    </li>

                    <li class="divider"></li>
                    <li><a href="<?php  echo $url_links['logout'] ?>"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                    </li>
                </ul>
                <!-- /.dropdown-user -->
            </li>
            <!-- /.dropdown -->
        </ul>
        <!-- /.navbar-top-links -->

        <div class="navbar-default sidebar" role="navigation">
            <div class="sidebar-nav navbar-collapse">
                <ul class="nav" id="side-menu">
                    <li class="sidebar-search">
                        <div class="input-group custom-search-form">
                            <input type="text" class="form-control" placeholder="Search...">
                                <span class="input-group-btn">
                                <button class="btn btn-default" type="button">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                        </div>
                        <!-- /input-group -->
                    </li>
                    <li>
                        <a href="<?php  echo $url_links['dashboard'] ?>"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                    </li>
                    <li>
                        <a href="<?php  echo $url_links['users'] ?>"><i class="fa fa-user fa-fw"></i> Users<span class="fa arrow"></span></a>

                        <!-- /.nav-second-level -->
                    </li>
                    <li>
                        <a href="<?php  echo $url_links['eco_pay'] ?>"><i class="fa fa-dollar fa-fw"></i> Ecocash Payments</a>
                    </li>
                    <li>
                        <a href="<?php  echo $url_links['net_pay'] ?>"><i class="fa fa-dollar fa-fw"></i> Netcash Payments</a>
                    </li>
                    <li>
                        <a href="<?php  echo $url_links['msgs'] ?>"><i class="fa fa-envelope fa-fw"></i> Messages</a>

                        <!-- /.nav-second-level -->
                    </li>
                    <li>
                        <a href="<?php  echo $url_links['change_password'] ?>"><i class="fa fa-lock fa-fw"></i> Change Password</a>

                        <!-- /.nav-second-level -->
                    </li>
                    <li>
                        <a href="<?php  echo $url_links['api_connect'] ?>"><i class="fa fa-external-link fa-fw"></i> API Connect</span></a>

                        <!-- /.nav-second-level -->
                    </li>
                    <li>
                        <a href="<?php  echo $url_links['send_notification'] ?>"><i class="fa fa-bell fa-fw"></i> Send Notification</a>

                        <!-- /.nav-second-level -->
                    </li>
                    <li>
                        <a href="<?php  echo $url_links['send_news'] ?>"><i class="fa fa-cloud fa-fw"></i> Send News</span></a>

                        <!-- /.nav-second-level -->
                    </li>
                </ul>
            </div>
            <!-- /.sidebar-collapse -->
        </div>
        <!-- /.navbar-static-side -->
    </nav>

    <div id="page-wrapper">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Dashboard</h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
        <div class="row">
            <div class="col-lg-12">


                    <div class="col-md-12">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h3 class="panel-title">Users</h3>
                            </div>
                            <div class="panel-body">
                                <div class=" table-responsive">

                                    <table class="table table-striped table-hover table-condensed">
                                        <thead>

                                        <tr>
                                            <th>#</th>
                                            <th>Name</th>
                                            <th>Phone Number</th>
                                            <th>Date of Birth</th>
                                            <th>Joined At</th>
                                            <th>Branch</th>
                                            <th>Action</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <?php

                                        foreach ($this->users as $user):
                                       //     $user = new \Application\Entity\Users();
                                            $dateOfBirth = $util->MillisecondsToDateTimeString($user->getDateOfBirth(),Constants::SHOW_DATE_OF_BIRTH);
                                            $createdAt = $util->MillisecondsToDateTimeString($user->getCreatedAt(),0);
                                            $branch = $user->getBranch();
                                          //  $branch = new \Application\Entity\Branches();

                                            ?>
                                            <tr>
                                                <td><?php echo $this->escapeHtml($user->getUserId()); ?></td>
                                                <td><?php echo $this->escapeHtml($user->getFirstName().' '.$user->getLastName()); ?></td>
                                                <td><?php echo $this->escapeHtml($user->getPhoneNumber()); ?></td>
                                                <td><?php echo $this->escapeHtml($dateOfBirth); ?></td>
                                                <td><?php echo $this->escapeHtml($createdAt); ?></td>
                                                <td><?php echo $this->escapeHtml($branch->getBranchName()); ?></td>
                                                <td><a href='<?php //echo $url_links['']; ?>' class='btn btn-info btn-xs'> More Details</a></td>
                                            </tr>
                                        <?php endforeach; ?>
                                        </tbody>
                                    </table>
                                </div>

                                <?php echo $this->paginationControl($this->users, 'Sliding', 'paginator.phtml',
                                    array('controllerAction'=>Constants::SHIRI_USERS)); ?>

                                    <a class="btn btn-default btn-lg btn-block" target="_blank" href="#">View All Users</a>

                            </div>
                        </div>
                    </div>

            </div>
            <!-- /.col-lg-8 -->
            <div class="col-lg-4">




            </div>
            <!-- /.col-lg-4 -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /#page-wrapper -->

</div>


<?= $this->render('layout/footer.phtml') ?>