<?php
//<!-- Bootstrap Core JavaScript -->
 $this->inlineScript()->prependFile($this->basePath('js/bootstrap.min.js'))
    //<!-- jQuery -->
    ->prependFile($this->basePath('js/jquery.min.js'))
    //<!-- Metis Menu Plugin JavaScript -->
    ->prependFile($this->basePath('bower_components/metisMenu/dist/metisMenu.min.js'))
//     <!-- Custom Theme JavaScript -->
    ->prependFile($this->basePath('js/sb-admin-2.js'));
$this->inlineScript()->captureStart();
echo <<<JS
   $(function () { formInit(); });

JS;
$this->inlineScript()->captureEnd();
echo $this->inlineScript();
?>


<div id = "footer">
            Copyright &copy; <?php use Application\Model\Constants;

            echo date('Y') . ' ' . Constants::SHIRI_NAME.'  '.'Privacy &amp; Terms' ?>

</div>

</body>
</html>
