<?php
use Application\Model\Constants;
use Application\SysConfigs\ProductInfo;
echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="author" content="Alois Mumera mumeraalois@gmail.com">
    <?php echo $this->headTitle(Constants::ADMIN_LOGIN )->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ->prependStylesheet($this->basePath('bower_components/metisMenu/dist/metisMenu.min.css'))
        ->prependStylesheet($this->basePath('css/sb-admin-2.css'))
        ->prependStylesheet($this->basePath('css/datepicker.min.css'))
        ->prependStylesheet($this->basePath('css/datepicker3.min.css'))
        ->prependStylesheet($this->basePath('bower_components/font-awesome/css/font-awesome.min.css')) ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',)); ?>


